### ISSUE TITLE
Showing Blank Page

### ISSUE THREAD

**Issue by aphwong** [DanDiplo/Umbraco.AuditLogViewer#11]
Envionment: Umbraco 10

Issue: Blank Page is showing when accessing Log Viewer
![image](https://user-images.githubusercontent.com/43560054/223713508-df1147ea-1120-408a-be6d-80aa453352ca.png)

Error Message: 
![image](https://user-images.githubusercontent.com/43560054/223713614-4dd6f6da-c481-46bd-affb-391cdc2c3252.png)

Could I ask how to solve this problem?

**Comment by DanDiplo** [comment]
Hi. I have it installed on a few v10 sites myself and I've not seen this error and nobody else has reported it. So I'd suspect it is to do with your particular set-up.

Usually these type of errors tend to arise because the JS in Umbraco hasn't updated. Have you tried restarting the application? Are you running on Windows? (I've never tested on Linux, I'm afraid). 

If you look in `App_Plugins` do you see the `DiploAuditLogViewer` folder and has it got contents? If so it should have installed OK. 

You can also try deleting temp Umbraco files in /umbraco/Data/TEMP/ folder. These will get regenerated on restart. As I say, normally these issues are fixed by restarting the application or reinstalling the Nuget package.

**Comment by aphwong** [comment]
![image](https://user-images.githubusercontent.com/43560054/224607663-93def45c-1b30-4396-9e36-7ab1abba9650.png)

Yes there are files and folder inside "App_Plugins" and I've also tried delete "TEMP" folder at "/umbraco/Data/".
Restart the server also don't work for me.
Here is the detail error in js file
![image](https://user-images.githubusercontent.com/43560054/224607427-d8dc9d30-6e87-416a-b33f-f1aa1d444508.png)

**Comment by aphwong** [comment]
Finally worked with the setting added below in appsetting.json.

"RuntimeMinification": {
        "UseInMemoryCache": true,
        "CacheBuster": "Timestamp"
      }

Not sure why it's work

**Comment by DanDiplo** [comment]
It certainly sounds like it is something to do with Umbraco and how it caches the minified JavaScript. My guess is that it was caching to disk before and that cache wasn't getting updated when you installed my package. Probably some issue in Smidge. Forcing it to use in memory cache allows the JS to regenerate properly and you get the latest updates, including the package scripts. 

Anyway, glad you got it resolved and hopefully this might help anyone else with the same issue.
