### ISSUE TITLE
'Delete' Function of Media items ascribed to the item creator, not the deleter

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [DanDiplo/Umbraco.AuditLogViewer#4]
When a Media Item is deleted,  the Audit Log reports the initial delete as "Move Media to Recycle Bin performed by user", correctly ie the audit log records the user who pressed 'delete'.

**### But** the **actual delete action** is ascribed to the original **creator** of the Media Item , rather than to the User who who pressed 'delete'. "Trashed media with Id: 39369 related to original parent media item with Id: 38807"

Note: for documents/pages actions are correctly reported in the Audit Log  - where both the Move to recycle Bin and the 'Trashed,,,, " ie the actions are allocated to the same person.

We are using Umbraco 7.13.2 with Diplo Audit Log Viewer v 1.0.4.
![image](https://user-images.githubusercontent.com/22772250/54623450-6a785700-4a63-11e9-9471-ee30fc606cea.png)

Thanks Fiona

**Comment by DanDiplo** [comment]
Hi! Apologies for the delay in answering, but I've been on holiday....

Anyway, just so you know, my viewer is only responsible for _displaying_ the audit trail that Umbraco records (in the `umbracoLog` table in the database). So if the information is inaccurate then that is down to Umbraco not recording the correct information. In your case it seems it stores the wrong User ID when a media file is finally deleted.

I did a little test to confirm this. What I found wa:

- If you deleted a media file then, as you say, it shows the correct "trashed" user information.
- If you delete a single file from the media recycle bin (ie. right click and select 'Delete' to just delete that one image) then that also displays the correct user.
- However, if you empty the recycle bin then it doesn't show the correct user as the one who deleted the item from the bin. When I tested it, it showed the admin user (who was also the creator).

I checked the `umbracoLog `table and could see that this was what information was stored there. So my viewer is showing the correct information in terms of it is displaying what Umbraco has stored. The issue seems to be down to Umbraco not recording the correct user, which I'm afraid I can't do anything about - but you can report issues here: https://github.com/umbraco/Umbraco-CMS/issues
